inherit_gem:
  theforeman-rubocop:
    - strictest.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

Metrics/BlockLength:
  Exclude:
    - 'lib/foreman_expire_hosts/engine.rb'

Style/FormatString:
  EnforcedStyle: percent
