inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  TargetRailsVersion: 5.1
  Exclude:
    - 'Rakefile'

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Naming/FileName:
  Exclude:
      - 'db/seeds.d/*'

Style/WordArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
