inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.1
  Exclude:
    - 'Rakefile'

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Naming/FileName:
  Exclude:
      - 'db/seeds.d/*'

Style/WordArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Metrics:
  Enabled: false
